export const testIds = {
  statusBar: {
    container: "statusbar-container",
    project: "statusbar-project",
    projectName: "statusbar-project-name",
    scope: "statusbar-scope",
    scopeText: "statusbar-scope-text",
    scopeToggle: "statusbar-scope-toggle",
    jumpToContexts: "statusbar-jump-to-contexts",
  },
  activityBar: {
    item: (workbenchId: "file" | "extensions" | "data" | "analysis" | "event") => `activitybar-item-${workbenchId}`,
    file: "activitybar-item-file",
    extensions: "activitybar-item-extensions",
    data: "activitybar-item-data",
    analysis: "activitybar-item-analysis",
    event: "activitybar-item-event",
  },
  extensions: {
    container: "extensions-workbench",
    emptyState: "extensions-empty-state",
    item: (extensionId: string) => `extensions-item-${encodeURIComponent(String(extensionId || ""))}`,
    toggle: (extensionId: string) => `extensions-toggle-${encodeURIComponent(String(extensionId || ""))}`,
    details: {
      container: "extensions-details",
      name: "extensions-details-name",
      id: "extensions-details-id",
      enabled: "extensions-details-enabled",
    },
  },
  sidebar: {
    container: "sidebar-container",
    viewsScroll: "sidebar-views-scroll",
    collapsedDock: "sidebar-collapsed-dock",
    view: {
      dashboards: "sidebar-view-dashboards",
      contexts: "sidebar-view-contexts",
      workbooks: "sidebar-view-workbooks",
      chat: "sidebar-view-chat",
    },
    viewBody: {
      dashboards: "sidebar-viewbody-dashboards",
      contexts: "sidebar-viewbody-contexts",
      workbooks: "sidebar-viewbody-workbooks",
      chat: "sidebar-viewbody-chat",
    },
    headers: {
      dashboards: "sidebar-dashboards-header",
      contexts: "sidebar-contexts-header",
      workbooks: "sidebar-workbooks-header",
      chat: "sidebar-chat-header",
    },
    project: {
      container: "sidebar-project",
      name: "sidebar-project-name",
    },
    activeContextJump: "sidebar-active-context-jump",
    scopeIndicator: "sidebar-scope-indicator",
    scopeText: "sidebar-scope-text",
  },
  contexts: {
    create: "contexts-create",
    refresh: "contexts-refresh",
    scopeToggle: "contexts-scope-toggle",
    scopeMode: "contexts-scope-mode",
    quickWorkbooks: {
      toggle: "contexts-quick-workbooks-toggle",
      container: "contexts-quick-workbooks",
    },
    card: {
      workbooksToggle: (contextId: string) => `contexts-card-workbooks-toggle-${encodeURIComponent(String(contextId || ""))}`,
      workbooksList: (contextId: string) => `contexts-card-workbooks-list-${encodeURIComponent(String(contextId || ""))}`,
    },
    modal: {
      name: "contexts-modal-name",
      workbookCheckbox: "contexts-modal-workbook-checkbox",
      save: "contexts-modal-save",
      cancel: "contexts-modal-cancel",
    },
    item: (contextId: string) => `contexts-item-${contextId}`,
    edit: (contextId: string) => `contexts-edit-${contextId}`,
    activate: (contextId: string) => `contexts-activate-${contextId}`,
    delete: (contextId: string) => `contexts-delete-${contextId}`,
    quickWorkbook: (workbookId: string) => `contexts-quick-workbook-${encodeURIComponent(String(workbookId || ""))}`,
  },
  chat: {
    input: "chat-input",
    send: "chat-send",
    newChat: "chat-new",
    history: "chat-history",
    settings: "chat-settings",
    popout: "chat-popout",
    contextChip: "chat-context-chip",
    contextMenu: "chat-context-menu",
    contextMenuGoToContexts: "chat-context-menu-go-to-contexts",
    contextItem: (contextId: string) => `chat-context-item-${encodeURIComponent(String(contextId || ""))}`,
    contextQuickWorkbook: (workbookId: string) =>
      `chat-context-quick-workbook-${encodeURIComponent(String(workbookId || ""))}`,
    scopeChip: "chat-scope-chip",
    activity: {
      container: "chat-activity",
      item: (stepId: string) => `chat-activity-item-${encodeURIComponent(String(stepId || ""))}`,
      toggle: "chat-activity-toggle",
    },
    message: (messageId: string) =>
      `chat-message-${encodeURIComponent(String(messageId || ""))}`,
    messageScope: (messageId: string) =>
      `chat-message-scope-${encodeURIComponent(String(messageId || ""))}`,
    emptyState: {
      container: "chat-empty-state",
      message: "chat-empty-state-message",
      jumpToContexts: "chat-empty-state-jump-contexts",
      loading: "chat-context-loading",
    },
    tabs: {
      panelChat: "chat-panel-chat",
      panelHistory: "chat-panel-history",
      panelSettings: "chat-panel-settings",
    },
    llmConfig: {
      provider: "chat-llm-provider",
      model: "chat-llm-model",
      modelSelect: "chat-llm-model-select",
      refreshModels: "chat-llm-refresh-models",
      apiKey: "chat-llm-apikey",
      baseUrl: "chat-llm-baseurl",
      save: "chat-llm-save",
      status: "chat-llm-status",
    },
    mentions: {
      menu: "chat-mention-menu",
      item: (kind: string, id: string) =>
        `chat-mention-item-${kind}-${encodeURIComponent(String(id || ""))}`,
    },
    refs: {
      container: "chat-refs",
      chip: (key: string) => `chat-ref-${encodeURIComponent(String(key || ""))}`,
      remove: (key: string) => `chat-ref-remove-${encodeURIComponent(String(key || ""))}`,
    },
    streaming: {
      container: "chat-streaming",
      content: "chat-streaming-content",
    },
  },
  toast: {
    center: "toast-center",
    message: "toast-message",
    dismiss: "toast-dismiss",
    kind: (kind: "success" | "error" | "info") => `toast-${kind}`,
  },
  inputDialog: {
    backdrop: "input-dialog-backdrop",
    title: "input-dialog-title",
    input: "input-dialog-input",
    cancel: "input-dialog-cancel",
    ok: "input-dialog-ok",
  },
  confirmDialog: {
    backdrop: "confirm-dialog-backdrop",
    dialog: "confirm-dialog",
    title: "confirm-dialog-title",
    message: "confirm-dialog-message",
    cancel: "confirm-dialog-cancel",
    confirm: "confirm-dialog-confirm",
  },
  unsavedCloseDialog: {
    backdrop: "unsaved-close-dialog-backdrop",
    dialog: "unsaved-close-dialog",
    title: "unsaved-close-dialog-title",
    message: "unsaved-close-dialog-message",
    save: "unsaved-close-dialog-save",
    dontSave: "unsaved-close-dialog-dont-save",
    cancel: "unsaved-close-dialog-cancel",
  },
  dashboards: {
    sidebar: {
      create: "dashboards-create",
      item: (dashboardId: string) => `dashboards-item-${dashboardId}`,
      contextMenu: {
        rename: "dashboards-context-rename",
        delete: "dashboards-context-delete",
      },
    },
    viewer: {
      addQuestionInput: "dashboards-add-question-input",
      addQuestionMentionMenu: "dashboards-add-question-mention-menu",
      addQuestionMentionItem: (kind: string, id: string) =>
        `dashboards-add-question-mention-item-${kind}-${encodeURIComponent(String(id || ""))}`,
      addQuery: "dashboards-add-query",
      refreshAll: "dashboards-refresh-all",
    },
    tile: {
      container: (queryId: string) => `dashboard-tile-${queryId}`,
      result: (queryId: string) => `dashboard-tile-result-${queryId}`,
      sizeSelect: (queryId: string) => `dashboard-tile-size-${queryId}`,
      vizSelect: (queryId: string) => `dashboard-tile-viz-${queryId}`,
      vizOption: (queryId: string, tileType: string) => `dashboard-tile-viz-${queryId}-${tileType}`,
      chartSelect: (queryId: string) => `dashboard-tile-chart-${queryId}`,
      chartOption: (queryId: string, chartType: string) => `dashboard-tile-chart-${queryId}-${chartType}`,
      refresh: (queryId: string) => `dashboard-tile-refresh-${queryId}`,
      remove: (queryId: string) => `dashboard-tile-remove-${queryId}`,
      editQuestion: (queryId: string) => `dashboard-tile-edit-question-${queryId}`,
      explain: (queryId: string) => `dashboard-tile-explain-${queryId}`,
      sources: (queryId: string) => `dashboard-tile-sources-${queryId}`,
      menu: (queryId: string) => `dashboard-tile-menu-${queryId}`,
      menuPanel: (queryId: string) => `dashboard-tile-menu-panel-${queryId}`,
      infoClose: (queryId: string) => `dashboard-tile-info-close-${queryId}`,
      sourcesPanel: (queryId: string) => `dashboard-tile-sources-panel-${queryId}`,
      explainPanel: (queryId: string) => `dashboard-tile-explain-panel-${queryId}`,
    },
  },
  documentViewer: {
    tabs: "document-viewer-tabs",
    tab: (docId: string) => `document-viewer-tab-${encodeURIComponent(String(docId || ""))}`,
    tabClose: (docId: string) => `document-viewer-tab-close-${encodeURIComponent(String(docId || ""))}`,
    tabContextMenu: "document-viewer-tab-context-menu",
    tabContextClose: "document-viewer-tab-context-close",
    tabContextCloseOthers: "document-viewer-tab-context-close-others",
    tabContextCloseSaved: "document-viewer-tab-context-close-saved",
    tabContextCloseAll: "document-viewer-tab-context-close-all",
    split: {
      container: "document-viewer-split-container",
      groupA: "document-viewer-group-a",
      groupB: "document-viewer-group-b",
      tabsA: "document-viewer-tabs-a",
      tabsB: "document-viewer-tabs-b",
      paneA: "document-viewer-pane-a",
      paneB: "document-viewer-pane-b",
      splitRight: "document-viewer-split-right",
      splitDown: "document-viewer-split-down",
      moveToOtherGroup: "document-viewer-move-to-other-group",
    },
    saveBar: "document-viewer-save-bar",
    saveButton: "document-viewer-save-button",
    content: "document-viewer-content",
    error: "document-viewer-error",
    errorClose: "document-viewer-error-close",
    loadError: "document-viewer-load-error",
    loadErrorClose: "document-viewer-load-error-close",
  },
  workbooks: {
    header: {
      create: "workbooks-create",
      refresh: "workbooks-refresh",
      collapseAll: "workbooks-collapse-all",
      search: "workbooks-search",
    },
    search: {
      input: "workbooks-search-input",
      clear: "workbooks-search-clear",
    },
    item: (workbookId: string) => `workbooks-item-${workbookId}`,
    toggle: (workbookId: string) => `workbooks-toggle-${workbookId}`,
    createMarkdown: (workbookId: string) => `workbooks-create-markdown-${workbookId}`,
    createDocument: (workbookId: string) => `workbooks-create-document-${workbookId}`,
    createFolder: (workbookId: string) => `workbooks-create-folder-${workbookId}`,
    action: (actionId: string, workbookId: string) => `workbooks-action-${actionId}-${workbookId}`,
    folder: (workbookId: string, folderName: string) =>
      `workbooks-folder-${workbookId}-${encodeURIComponent(String(folderName || ""))}`,
    folderCreateMarkdown: (workbookId: string, folderName: string) =>
      `workbooks-folder-create-markdown-${workbookId}-${encodeURIComponent(String(folderName || ""))}`,
    folderAddFiles: (workbookId: string, folderName: string) =>
      `workbooks-folder-addfiles-${workbookId}-${encodeURIComponent(String(folderName || ""))}`,
    folderAction: (actionId: string, workbookId: string, folderName: string) =>
      `workbooks-folder-action-${actionId}-${workbookId}-${encodeURIComponent(String(folderName || ""))}`,
    doc: (workbookId: string, docPathOrName: string) =>
      `workbooks-doc-${workbookId}-${encodeURIComponent(String(docPathOrName || ""))}`,
    docRename: (workbookId: string, docRelativePath: string) =>
      `workbooks-doc-rename-${workbookId}-${encodeURIComponent(String(docRelativePath || ""))}`,
    docMove: (workbookId: string, docRelativePath: string) =>
      `workbooks-doc-move-${workbookId}-${encodeURIComponent(String(docRelativePath || ""))}`,
    docDelete: (workbookId: string, docRelativePath: string) =>
      `workbooks-doc-delete-${workbookId}-${encodeURIComponent(String(docRelativePath || ""))}`,
    contextMenu: {
      docRename: "workbooks-doc-context-rename",
      docMove: "workbooks-doc-context-move",
      docDelete: "workbooks-doc-context-delete",
      folderMove: "workbooks-folder-context-move",
      folderRename: "workbooks-folder-context-rename",
      folderDelete: "workbooks-folder-context-delete",
    },
    collision: {
      backdrop: "collision-dialog-backdrop",
      dialog: "collision-dialog",
      title: "collision-dialog-title",
      message: "collision-dialog-message",
      renameInput: "collision-dialog-rename-input",
      rename: "collision-dialog-rename",
      overwrite: "collision-dialog-overwrite",
      skip: "collision-dialog-skip",
      applyAll: "collision-dialog-apply-all",
    },
    moveFolder: {
      backdrop: "move-folder-dialog-backdrop",
      dialog: "move-folder-dialog",
      title: "move-folder-title",
      workbookSelect: "move-folder-workbook-select",
      folderInput: "move-folder-folder-input",
      error: "move-folder-error",
      noop: "move-folder-noop",
      ok: "move-folder-ok",
      cancel: "move-folder-cancel",
    },
    moveDoc: {
      backdrop: "move-doc-dialog-backdrop",
      dialog: "move-doc-dialog",
      title: "move-doc-title",
      workbookSelect: "move-doc-workbook-select",
      folderSelect: "move-doc-folder-select",
      filenameInput: "move-doc-filename-input",
      error: "move-doc-error",
      noop: "move-doc-noop",
      ok: "move-doc-ok",
      cancel: "move-doc-cancel",
    },
  },
  // NOTE: legacy duplicate `documentViewer` keys were removed to avoid object-literal overwrite bugs.
  notebook: {
    viewer: "notebook-viewer",
    cell: (index: number) => `notebook-cell-${index}`,
    runCell: (index: number) => `notebook-cell-run-${index}`,
    output: (index: number) => `notebook-cell-output-${index}`,
  },
  spreadsheet: {
    viewer: "spreadsheet-viewer",
    container: "spreadsheet-container",
  },
} as const;
