export interface DashboardQuery {
  id: string;
  question: string;
  title?: string; // Optional custom title (defaults to question if not set)
  queryType: "count" | "filter" | "date_range" | "aggregate" | "custom";
  tileType?: "counter" | "counter_warning" | "graph" | "table" | "text" | "date" | "color"; // Visualization type
  workbookId?: string;
  filters?: Record<string, any>;
  createdAt: string;
  lastRun?: string;
  result?: DashboardResult;
  generatedCode?: string; // Python code generated by MCP server
  // Tile layout properties
  tileSize?: "small" | "medium" | "large" | "full-width"; // Size of the tile
  tilePosition?: { x: number; y: number }; // Grid position (for drag-and-drop)
}

export interface DashboardResult {
  // Legacy format (for backward compatibility)
  value?: number | string;
  data?: Array<Record<string, any>>;
  chartType?: "table" | "bar" | "line" | "pie" | "card";
  metadata?: Record<string, any>;

  // New MCP format
  type?: "counter" | "counter_warning" | "graph" | "table" | "text" | "date" | "color" | "error";

  // Counter types
  label?: string;
  subtitle?: string;
  level?: "success" | "warning" | "danger"; // For counter_warning
  threshold?: number;
  items?: string[]; // For counter_warning - list of items

  // Date type
  date?: string; // ISO date
  daysUntil?: number;

  // Color/status type
  color?: "green" | "yellow" | "red";
  message?: string;

  // Graph type
  html?: string; // Plotly HTML for interactive charts

  // Table type
  columns?: string[];
  rows?: Array<Record<string, any>>;
  totalRows?: number;

  // Text type
  content?: string;
  format?: "markdown" | "plain";

  // Error type
  error?: string;
}

export interface Dashboard {
  id: string;
  name: string;
  queries: DashboardQuery[];
  createdAt: string;
  updatedAt: string;
}
